# Generated by Django 6.0.4 on 2026-04-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0002_turno_nombre_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
