# Generated by Django 6.0.4 on 2026-04-13 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0003_turno_telefono_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono/WhatsApp')),
            ],
            options={
                'verbose_name': 'Clienta',
                'verbose_name_plural': 'Clientas',
            },
        ),
        migrations.RemoveField(
            model_name='turno',
            name='nombre_cliente',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='telefono_cliente',
        ),
        migrations.AddField(
            model_name='turno',
            name='notas_tecnicas',
            field=models.TextField(blank=True, help_text='Ej: Tintura 7.1, Mechas con gorra, Alisado fuerte, etc.', null=True, verbose_name='Notas del servicio'),
        ),
        migrations.AddField(
            model_name='turno',
            name='clienta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='Turnos.clienta'),
        ),
    ]
