# Generated by Django 6.0.4 on 2026-04-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0004_clienta_remove_turno_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='pagado_hasta_ahora',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto ya pagado ($)'),
        ),
        migrations.AddField(
            model_name='turno',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio del Trabajo ($)'),
        ),
    ]
